/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package harpo

import org.junit.jupiter.api.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun appHasAGreeting() {

        //assertNotNull("", "app should have a greeting")
    }
}
